export const filterData = [
    {id:1,
     filter: "kişilər"},
    {id:2,
     filter: "qadınlar"},
    {id:3,
     filter: "24 saat"},
    {id:4,
     filter: "qadınlar üçün ayrı"},
    {id:5,
     filter: "fərdi treyner"},
    {id:6,
     filter: "ödənişsiz treyner xidməti"},
    {id:7,
     filter: "mənə yaxın"},
    {id:8,
     filter: "kampaniya"},
]