export const regionsData = [
       {id:1,
        region: 'Abşeron r' },
       {id:2,
        region: 'Binəqədi r' },
       {id:3,
        region: 'Nərimanov r' },
       {id:4,
        region: 'Nəsimi r' },
       {id:5,
        region: 'Nizami r' },
       {id:6,
        region: 'Pirallahı r' },
       {id:7,
        region: 'Sabunçu r' },
       {id:8,
        region: 'Səbail r' },
       {id:9,
        region: 'Suraxanı r' },
       {id:10,
        region: 'Xətai r' },
       {id:11,
        region: 'Xəzər r' },
       {id:12,
        region: 'Yasamal r' },
      ];
